FROM node:8
WORKDIR /app

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

ARG username
ARG password

RUN git clone https://${username}:${password}@github.com/username/repository.git

ENTRYPOINT ["sleep 10"]

RUN npm install
COPY . /app
CMD npm start
EXPOSE 3000


